"use client";
import { ApiOutlined, MailOutlined, NodeIndexOutlined } from "@ant-design/icons";
import { Alert, Button, Card, Checkbox, Collapse, Drawer, Form, Input, InputNumber, Radio, Result, Select, Space, Steps, Switch, Tag, Upload, message } from "antd";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { services } from "@/mocks/data";
import type { Permission } from "@/services/contracts/gateway";
import { CredentialsPanel, type ServiceTemplate } from "./Credentials";
import styles from "./Gateway.module.css";

const permOptions=[{label:"允许",value:"allow"},{label:"每次确认",value:"confirm"},{label:"禁止",value:"deny"}];

function BasicInfo({kind,template,onTemplateChange}:{kind:"MCP"|"API"|"邮箱";template:ServiceTemplate;onTemplateChange:(value:ServiceTemplate)=>void}){const options=kind==="MCP"?[{label:"通用远程 MCP",value:"generic"},{label:"百度网盘 MCP",value:"baidu"}]:kind==="API"?[{label:"通用 API",value:"generic"},{label:"印象笔记 EDAM",value:"evernote"}]:[{label:"QQ 邮箱",value:"qq"},{label:"163 邮箱",value:"163"},{label:"通用邮箱",value:"generic"}];return <Form layout="vertical" className={styles.formGrid}><Form.Item label="服务名称" required><Input placeholder={template==="evernote"?"例如：我的印象笔记":template==="baidu"?"例如：我的百度网盘":"输入服务名称"}/></Form.Item><Form.Item label="服务模板"><Select value={template} options={options} onChange={onTemplateChange}/></Form.Item><Form.Item label="图标"><Upload><Button>上传图标</Button></Upload></Form.Item><Form.Item label="说明" className={styles.span2}><Input.TextArea rows={3} placeholder="说明这个服务可以提供什么能力"/></Form.Item></Form>}
function OAuthFields(){return <div className={styles.formGrid}><Form.Item label="授权地址"><Input placeholder="https://.../authorize"/></Form.Item><Form.Item label="令牌地址"><Input placeholder="https://.../token"/></Form.Item><Form.Item label="客户端编号"><Input placeholder="模拟客户端编号"/></Form.Item><Form.Item label="授权范围"><Input placeholder="read write"/></Form.Item><Form.Item label="PKCE"><Switch defaultChecked/> 启用</Form.Item><Form.Item label="回调地址"><Input placeholder="https://gate.example.com/oauth/callback"/></Form.Item><Form.Item label="访问令牌有效期"><InputNumber min={60} defaultValue={3600} addonAfter="秒" style={{width:"100%"}}/></Form.Item><Form.Item label="刷新令牌"><Switch defaultChecked/> 支持</Form.Item></div>}
function McpAddress({template}:{template:ServiceTemplate}){return <Form layout="vertical"><div className={styles.formGrid}><Form.Item label="MCP 地址" required><Input defaultValue={template==="baidu"?"https://mcp-pan.baidu.com/sse":undefined} placeholder="https://mcp.example.com/mcp"/></Form.Item><Form.Item label="传输方式"><Select defaultValue={template==="baidu"?"SSE":"auto"} options={["自动","Streamable HTTP","SSE"].map((x,i)=>({label:x,value:i?x:"auto"}))}/></Form.Item></div><Collapse ghost items={[{key:"advanced",label:"高级连接配置",children:<div className={styles.formGrid}><Form.Item label="超时时间"><InputNumber defaultValue={30} addonAfter="秒" style={{width:"100%"}}/></Form.Item><Form.Item label="重试次数"><InputNumber defaultValue={2} min={0} max={5} style={{width:"100%"}}/></Form.Item><Form.Item label="TLS"><Switch defaultChecked/> 校验证书</Form.Item><Form.Item label="用户代理"><Input defaultValue="PersonalGateway/0.2"/></Form.Item></div>}]} /></Form>}
function TestCapabilities({mail=false,configure=false}:{mail?:boolean;configure?:boolean}){const list=mail?["搜索邮件","读取邮件","查看附件信息","下载附件","发送邮件","移动邮件","删除邮件"]:["搜索内容","读取详情","新建内容","更新内容","删除内容"];const tested=(label:string)=>message.success(label+"成功（Mock）");return <Space direction="vertical" size={14} style={{width:"100%"}}><Alert showIcon type="success" message={mail?"收件测试和发件测试均成功":"initialize → tools/list → 能力发现完成"} description="这是 Mock 测试结果，没有发起真实连接。"/><Space wrap><Button type="primary" onClick={()=>tested("连接测试")}>测试连接</Button>{mail?<><Button onClick={()=>tested("收件测试")}>测试收件</Button><Button onClick={()=>tested("发件测试")}>测试发件</Button></>:null}</Space><Collapse items={[{key:"caps",label:"已发现 "+list.length+" 项原始能力",children:<Space direction="vertical" style={{width:"100%"}}>{list.map((x,i)=><div className={styles.capRow} key={x}><span><strong>{x}</strong><br/><small className={styles.muted}>{i<3?"只读能力":i===list.length-1?"高危能力":"写入能力"}</small></span>{configure?<Select defaultValue={(i<2?"allow":i===list.length-1?"deny":"confirm") as Permission} options={permOptions}/>:<Tag>{i<3?"只读":"写入"}</Tag>}</div>)}</Space>}]} /></Space>}
function ApiDefinition(){const [mode,setMode]=useState<"openapi"|"manual">("openapi");return <Form layout="vertical"><Form.Item label="API 定义方式"><Radio.Group value={mode} onChange={event=>setMode(event.target.value)} optionType="button" buttonStyle="solid" options={[{label:"OpenAPI",value:"openapi"},{label:"手工配置",value:"manual"}]}/></Form.Item><Card size="small" title={mode==="openapi"?"OpenAPI 导入":"手工接口定义"}>{mode==="openapi"?<Space direction="vertical" style={{width:"100%"}}><Input placeholder="OpenAPI 地址"/><Input.TextArea rows={4} placeholder="粘贴 JSON 或 YAML"/><Upload><Button>上传 JSON / YAML</Button></Upload></Space>:<div className={styles.formGrid}><Form.Item label="请求方法"><Select defaultValue="GET" options={["GET","POST","PUT","PATCH","DELETE"].map(x=>({label:x,value:x}))}/></Form.Item><Form.Item label="接口路径"><Input placeholder="/v1/items/{id}"/></Form.Item><Form.Item label="查询参数"><Input.TextArea rows={3} placeholder="参数名称、类型、是否必填"/></Form.Item><Form.Item label="请求头"><Input.TextArea rows={3} placeholder="请求头定义"/></Form.Item><Form.Item label="请求体"><Input.TextArea rows={3} placeholder="JSON 请求体"/></Form.Item><Form.Item label="响应示例"><Input.TextArea rows={3} placeholder="响应示例"/></Form.Item><Form.Item label="数据提取路径"><Input placeholder="$.data.items"/></Form.Item><Form.Item label="数据结构"><Input.TextArea rows={3} placeholder="JSON Schema"/></Form.Item></div>}</Card></Form>}
function MailConfig({smtp=false}:{smtp?:boolean}){return <Form layout="vertical" className={styles.formGrid}><Form.Item label="服务器地址" required><Input defaultValue={smtp?"smtp.qq.com":"imap.qq.com"}/></Form.Item><Form.Item label="端口" required><InputNumber defaultValue={smtp?465:993} style={{width:"100%"}}/></Form.Item><Form.Item label="TLS"><Switch defaultChecked/> 启用</Form.Item>{smtp?<Form.Item label="回复地址"><Input placeholder="可选回复地址"/></Form.Item>:null}</Form>}

export function ServiceWizard(){
 const router=useRouter();const [kind,setKind]=useState<"MCP"|"API"|"邮箱"|null>(null);const [step,setStep]=useState(0);const [done,setDone]=useState(false);const [interactive,setInteractive]=useState(false);const [template,setTemplate]=useState<ServiceTemplate>("generic");const [credentialValid,setCredentialValid]=useState(false);
 const titles=kind==="MCP"?["基本信息","地址与传输","认证与凭证","测试连接","发现能力","保存"]:kind==="API"?["基本信息","API 定义","认证与凭证","接口预览","测试","保存"]:kind==="邮箱"?["基本信息","认证与凭证","IMAP","SMTP","测试","保存"]:["选择类型"];
 useEffect(()=>{const ready=window.setTimeout(()=>setInteractive(true),0);const h=(e:BeforeUnloadEvent)=>{if(!done){e.preventDefault();e.returnValue=""}};window.addEventListener("beforeunload",h);return()=>{window.clearTimeout(ready);window.removeEventListener("beforeunload",h)}},[done]);
 const reset=(v:"MCP"|"API"|"邮箱")=>{setKind(v);setStep(0);setTemplate(v==="邮箱"?"qq":"generic");setCredentialValid(false)};
 const finish=()=>{setDone(true);message.success("服务已保存为模拟数据");window.setTimeout(()=>router.push("/services"),500)};
 const content=()=>{
  if(!kind)return <div className={styles.choiceGrid}>{[{k:"MCP",i:<NodeIndexOutlined/>,t:"MCP 服务",d:"连接一个已经存在的远程 MCP 服务"},{k:"API",i:<ApiOutlined/>,t:"API 服务",d:"导入 OpenAPI，或手工配置完整接口"},{k:"邮箱",i:<MailOutlined/>,t:"邮箱服务",d:"快速配置 QQ、163 或通用邮箱"}].map(x=><Button key={x.k} className={styles.choice} onClick={()=>reset(x.k as "MCP"|"API"|"邮箱")}><span className={styles.serviceType}>{x.i}</span><strong>{x.t}</strong><span className={styles.muted}>{x.d}</span></Button>)}</div>;
  if(kind==="MCP"){if(step===0)return <BasicInfo kind={kind} template={template} onTemplateChange={setTemplate}/>;if(step===1)return <McpAddress template={template}/>;if(step===2)return <CredentialsPanel key={`${kind}-${template}`} template={template} onValidationChange={setCredentialValid}/>;if(step===3)return <Alert type="success" showIcon message="模拟连接测试成功" description="初始化响应正常，凭证和请求 URL 已脱敏。"/>;if(step===4)return <TestCapabilities/>;return <Result status="success" title="远程 MCP 服务配置就绪" subTitle="将保存原始能力数据结构快照。"/>}
  if(kind==="API"){if(step===0)return <BasicInfo kind={kind} template={template} onTemplateChange={setTemplate}/>;if(step===1)return <ApiDefinition/>;if(step===2)return <CredentialsPanel key={`${kind}-${template}`} template={template} onValidationChange={setCredentialValid}/>;if(step===3)return <Collapse defaultActiveKey={["ops"]} items={[{key:"ops",label:"3 个原始 API 接口",children:<Space direction="vertical"><Tag>GET /items</Tag><Tag>GET /items/:id</Tag><Tag color="warning">POST /items · 写入</Tag></Space>}]} />;if(step===4)return <Alert type="success" showIcon message="模拟接口测试成功" description="基础地址、上游认证和响应结构校验通过。"/>;return <Result status="success" title="API 服务配置就绪" subTitle="保存基础地址、认证和原始接口。"/>}
  if(step===0)return <BasicInfo kind="邮箱" template={template} onTemplateChange={setTemplate}/>;
  if(step===1)return <CredentialsPanel key={`${kind}-${template}`} template={template} onValidationChange={setCredentialValid}/>;
  if(step===2)return <MailConfig/>;if(step===3)return <MailConfig smtp/>;if(step===4)return <TestCapabilities mail/>;return <Result status="success" title="邮箱服务配置就绪" subTitle="保存 IMAP/SMTP 连接和 7 项原始能力。"/>;
 };
 if(done)return <Result status="success" title="服务已保存" extra={<Button type="primary" onClick={()=>router.push("/services")}>返回全部服务</Button>}/>;
 const isCredentialStep=Boolean(kind)&&(kind==="邮箱"?step===1:step===2);
 const kindLabel=kind==="邮箱"?"邮箱服务":kind?kind+" 服务":"新增服务";
 const advance=()=>{if(isCredentialStep&&!credentialValid){message.error("请完整填写凭证并确认其未过期");return}if(step===titles.length-1)finish();else setStep(x=>x+1)};
 return <div className={styles.wizard} data-testid="wizard"><Card><div className={styles.selectedCount}><strong>{kindLabel}</strong><span>第 {step+1}/{titles.length} 步 · {titles[step]}</span></div><Steps current={step} items={titles.map(title=>({title}))}/><div className={styles.stepWrap}><h3 className={styles.stepTitle} data-testid="wizard-title">{kind?kindLabel+" · ":""}{titles[step]}</h3>{content()}</div><div className={styles.actions} data-testid="wizard-actions"><Button disabled={!interactive||!kind||step===0} onClick={()=>setStep(x=>Math.max(0,x-1))}>上一步</Button><Button type="primary" disabled={!interactive||!kind} onClick={advance}>{!kind?"下一步":step===titles.length-1?"保存":isCredentialStep?"测试并继续":"下一步"}</Button></div></Card></div>
}

function ServiceSelection(){return <><Alert type="info" showIcon message="选择一个或多个服务及其原始能力" description="只读能力默认选择；写入和高危能力默认不选择。权限将在第 5 步逐项设置。" style={{marginBottom:16}}/><div className={styles.selectedCount}><strong>已选择 7 项能力</strong><span>可按服务展开或收起；勾选父节点不会改变展开状态</span></div><Space direction="vertical" style={{width:"100%"}}>{services.map(service=><Collapse key={service.id} items={[{key:service.id,label:<Space><Checkbox defaultChecked={service.id!=="office-api"} onClick={event=>event.stopPropagation()}/><strong>{service.name}</strong><Tag>{service.type} 服务</Tag></Space>,children:<Space direction="vertical" style={{width:"100%"}}>{service.capabilities.map(capability=><div key={capability.id} className={styles.capRow}><Checkbox defaultChecked={capability.risk==="read"}><strong>{capability.name}</strong><br/><small className={styles.muted}>{capability.id} · {capability.risk==="read"?"只读":"写入"} · {capability.risk==="delete"?"高":"中"}风险</small></Checkbox><Tag>{capability.risk==="read"?"默认选择":"默认不选"}</Tag></div>)}</Space>}]} />)}</Space></>}
function PermissionEditor(){return <><Alert type="info" showIcon message="权限最终落实到每项能力" description="服务级策略用于批量设置；每项能力固定支持允许、每次确认和禁止。" style={{marginBottom:16}}/><Space direction="vertical" style={{width:"100%"}}>{services.slice(0,3).map(service=><Collapse key={service.id} defaultActiveKey={service.id==="qq-mail"?[service.id]:[]} items={[{key:service.id,label:<Space><strong>{service.name}</strong><Select aria-label={service.name+"快捷策略"} defaultValue="readonly" onClick={event=>event.stopPropagation()} options={[{label:"仅允许只读",value:"readonly"},{label:"不包含该服务",value:"none"},{label:"自定义",value:"custom"}]}/></Space>,children:service.capabilities.map(capability=><div className={styles.permissionRow} key={capability.id}><span><strong>{capability.name}</strong><br/><small className={styles.muted}>{capability.risk==="read"?"只读能力":capability.risk==="delete"?"高危能力":"写入能力"}</small></span><Radio.Group aria-label={capability.name+"权限"} optionType="button" buttonStyle="solid" defaultValue={capability.permission} options={permOptions}/></div>)}]}/>)}</Space></>}
function CallerStep(){return <Form layout="vertical"><Alert type="info" showIcon message="一个端点允许多个调用方" description="每个调用方拥有独立身份或凭证，可单独统计、停用和撤销。" style={{marginBottom:16}}/><div className={styles.formGrid}><Form.Item label="调用方名称" required><Input defaultValue="ChatGPT" placeholder="例如：ChatGPT、Claude 或私人 GPT"/></Form.Item><Form.Item label="调用方状态"><Radio.Group defaultValue="enabled" options={[{label:"启用",value:"enabled"},{label:"停用",value:"disabled"}]}/></Form.Item></div><Button type="dashed" block>添加另一个调用方</Button></Form>}
function EndpointProtocol({protocol,setProtocol}:{protocol:string;setProtocol:(v:string)=>void}){return <div className={styles.choiceGrid}>{[{id:"MCP",title:"MCP 端点",desc:"将 MCP、API 或邮箱服务统一发布为可供 AI 客户端调用的 MCP 端点。"},{id:"OpenAPI",title:"OpenAPI API 端点",desc:"将 MCP、API 或邮箱服务统一发布为标准 HTTP API，并生成 OpenAPI 文档。"}].map(x=><Button key={x.id} type={protocol===x.id?"primary":"default"} className={styles.choice} onClick={()=>setProtocol(x.id)}><strong>{x.title}</strong><span>{x.desc}</span></Button>)}<Card className={styles.span2} size="small"><Form layout="vertical">{protocol==="MCP"?<div className={styles.formGrid}><Form.Item label="传输方式"><Select defaultValue="Streamable HTTP" options={["Streamable HTTP","SSE 兼容模式"].map(x=>({label:x,value:x}))}/></Form.Item><Form.Item label="MCP 协议版本"><Select defaultValue="2025-06-18" options={[{label:"2025-06-18",value:"2025-06-18"},{label:"2024-11-05",value:"2024-11-05"}]}/></Form.Item><Form.Item label="启用会话"><Switch defaultChecked/></Form.Item><Form.Item label="端点路径预览"><Input readOnly value="/mcp/personal-data-readonly"/></Form.Item></div>:<div className={styles.formGrid}><Form.Item label="API 基础路径"><Input defaultValue="/api/personal-data"/></Form.Item><Form.Item label="OpenAPI 文档版本"><Select defaultValue="3.1.0" options={["3.1.0","3.0.3"].map(x=>({label:x,value:x}))}/></Form.Item><Form.Item label="API 版本号"><Input defaultValue="v1"/></Form.Item><Form.Item label="服务地址预览"><Input readOnly value="https://gate.example.com/api/personal-data"/></Form.Item><Form.Item label="OpenAPI 文档地址预览" className={styles.span2}><Input readOnly value="https://gate.example.com/openapi/personal-data.json"/></Form.Item></div>}</Form></Card></div>}
function ConversionEditor({service,protocol}:{service:typeof services[number];protocol:string}){const [open,setOpen]=useState(false);const direction=service.type+" → "+(protocol==="MCP"?"MCP":"OpenAPI");const external=service.type==="邮箱"?(protocol==="MCP"?"search_emails":"POST /mail/search"):service.type==="API"?(protocol==="MCP"?"files_search":"GET /files/search"):(protocol==="MCP"?"market_quote":"POST /market/quote");return <><Card size="small"><div className={styles.entityTop}><div><strong>{service.name}</strong><p className={styles.muted}>{direction} · {service.capabilities.length} 项原始能力</p></div><Tag color="blue">{direction}</Tag></div><Collapse items={[{key:"preview",label:"转换结果预览",children:<ul>{service.capabilities.slice(0,3).map(c=><li key={c.id}>{c.name} → <code>{external}</code></li>)}</ul>}]} /><Button block onClick={()=>setOpen(true)}>编辑能力转换</Button></Card><Drawer open={open} onClose={()=>setOpen(false)} title={service.name+" · "+direction} width={720} placement="right"><Form layout="vertical"><Alert type="info" showIcon message={"来源服务："+service.name} description="基础地址、IMAP/SMTP 与上游认证沿用服务配置，不在端点中重复填写。" style={{marginBottom:16}}/><div className={styles.formGrid}><Form.Item label={protocol==="MCP"?"MCP 能力名称":"对外操作编号"}><Input defaultValue={external.replace(/[^a-z_]/g,"_")}/></Form.Item><Form.Item label="显示名称"><Input defaultValue={service.capabilities[0].name}/></Form.Item><Form.Item label="描述" className={styles.span2}><Input.TextArea rows={2} defaultValue={service.capabilities[0].description}/></Form.Item><Form.Item label="输入数据结构"><Input.TextArea className={styles.schemaEditor} rows={5} defaultValue={'{"type":"object","properties":{"query":{"type":"string"}}}'}/></Form.Item><Form.Item label="输出数据结构"><Input.TextArea className={styles.schemaEditor} rows={5} defaultValue={'{"type":"object","properties":{"items":{"type":"array"}}}'}/></Form.Item></div><Collapse items={[
 {key:"request",label:service.type==="API"?"API 请求映射":"请求与参数映射",children:<div className={styles.formGrid}><Form.Item label="原始接口或能力"><Input readOnly value={service.capabilities[0].id}/></Form.Item><Form.Item label="请求方法"><Select defaultValue={protocol==="MCP"?"GET":"POST"} options={["GET","POST","DELETE"].map(x=>({label:x,value:x}))}/></Form.Item><Form.Item label="对外路径"><Input defaultValue={protocol==="MCP"?"/upstream/search":"/mail/search"}/></Form.Item><Form.Item label="路径参数映射"><Input placeholder="id → path.id"/></Form.Item><Form.Item label="查询参数映射"><Input placeholder="query → query.q"/></Form.Item><Form.Item label="请求头参数映射"><Input placeholder="仅允许安全请求头"/></Form.Item><Form.Item label="请求体参数映射" className={styles.span2}><Input.TextArea rows={3}/></Form.Item></div>},
 {key:"response",label:"返回结果与安全限制",children:<div className={styles.formGrid}><Form.Item label="成功状态码"><Input defaultValue="200, 201"/></Form.Item><Form.Item label="JSONPath"><Input defaultValue="$.data"/></Form.Item><Form.Item label="保留字段"><Input placeholder="id,title,createdAt"/></Form.Item><Form.Item label="排除字段"><Input placeholder="token,raw_headers"/></Form.Item><Form.Item label="最大返回记录数"><InputNumber defaultValue={50} style={{width:"100%"}}/></Form.Item><Form.Item label="最大响应大小"><InputNumber defaultValue={512} addonAfter="KB" style={{width:"100%"}}/></Form.Item><Form.Item label="错误码映射"><Input.TextArea rows={3}/></Form.Item><Form.Item label="敏感字段脱敏"><Switch defaultChecked/></Form.Item></div>},
 {key:"mcp",label:"协议专用选项",children:<div className={styles.formGrid}><Form.Item label="能力名称前缀"><Input placeholder="mail_"/></Form.Item><Form.Item label="同步上游结构变更"><Switch defaultChecked/></Form.Item><Form.Item label="包含正文"><Switch/></Form.Item><Form.Item label="允许附件"><Switch/></Form.Item><Form.Item label="隐藏上游真实路径"><Switch defaultChecked/></Form.Item><Form.Item label="超时"><InputNumber defaultValue={30} addonAfter="秒"/></Form.Item></div>}
 ]}/><div className={styles.actions}><Button onClick={()=>setOpen(false)}>取消</Button><Button type="primary" onClick={()=>{setOpen(false);message.success("Mock 转换配置已保存")}}>保存转换</Button></div></Form></Drawer></>}
function ConversionStep({protocol}:{protocol:string}){return <><Alert type="info" showIcon message="转换发生在端点发布" description="根据上游服务类型与发布协议自动生成转换结果，可逐项修改名称、数据结构、映射与限制。" style={{marginBottom:16}}/><div className={styles.cards}>{services.slice(0,3).map(s=><ConversionEditor key={s.id} service={s} protocol={protocol}/>)}</div></>}
function EndpointAuth({protocol}:{protocol:string}){const initial=protocol==="MCP"?"OAuth 2.1":"API Key";const options=protocol==="MCP"?["OAuth 2.1","Bearer Token","无认证，仅开发环境"]:["API Key","Bearer Token","OAuth 2.0（预留）"];const [selected,setSelected]=useState<string>();const method=selected&&options.includes(selected)?selected:initial;const noAuth=method.startsWith("无认证");const oauth=method.startsWith("OAuth");return <Form layout="vertical"><Alert type="info" showIcon message="这里只配置下游调用方认证；上游认证由服务接入管理。" style={{marginBottom:16}}/><div className={styles.formGrid}><Form.Item label="端点认证方式"><Radio.Group value={method} onChange={event=>setSelected(event.target.value)} options={options.map(x=>({label:x,value:x}))}/></Form.Item>{!noAuth?<Form.Item label="令牌有效期" required><Select defaultValue="90d" options={[{label:"30 天",value:"30d"},{label:"90 天",value:"90d"},{label:"180 天",value:"180d"},{label:"长期有效",value:"never"}]}/></Form.Item>:null}</div>{oauth?<Card size="small" title="OAuth 配置"><OAuthFields/></Card>:!noAuth?<Card size="small" title={method+" 配置"}><div className={styles.formGrid}><Form.Item label="请求头名称"><Input defaultValue={method==="API Key"?"X-API-Key":"Authorization"}/></Form.Item><Form.Item label={method==="API Key"?"密钥前缀":"令牌前缀"}><Input defaultValue={method==="API Key"?"pg_":"Bearer "}/></Form.Item></div></Card>:<Alert type="warning" showIcon message="仅建议在本地开发环境关闭认证"/>}</Form>}
export function EndpointWizard(){
 const router=useRouter();const [step,setStep]=useState(0);const [protocol,setProtocol]=useState("MCP");const [done,setDone]=useState(false);const [interactive,setInteractive]=useState(false);const titles=["基本信息","发布协议","服务与能力","发布配置","权限策略","端点认证","调用方","测试与发布"];
 useEffect(()=>{const ready=window.setTimeout(()=>setInteractive(true),0);const h=(e:BeforeUnloadEvent)=>{if(!done){e.preventDefault();e.returnValue=""}};window.addEventListener("beforeunload",h);return()=>{window.clearTimeout(ready);window.removeEventListener("beforeunload",h)}},[done]);
 const endpointLabel=protocol==="MCP"?"MCP 端点":"OpenAPI API 端点";
 const content=[
  <Form key="a" layout="vertical" className={styles.formGrid}><Form.Item label="端点名称" required><Input defaultValue="个人数据只读端点"/></Form.Item><Form.Item label="端点标识" required><Input defaultValue="personal-data-readonly"/></Form.Item><Form.Item label="图标"><Upload><Button>上传图标</Button></Upload></Form.Item><Form.Item label="状态"><Radio.Group defaultValue="draft" options={[{label:"草稿",value:"draft"},{label:"启用",value:"enabled"}]}/></Form.Item><Form.Item label="说明" className={styles.span2}><Input.TextArea rows={3}/></Form.Item></Form>,
  <EndpointProtocol key="b" protocol={protocol} setProtocol={setProtocol}/>,
  <ServiceSelection key="c"/>,<ConversionStep key="d" protocol={protocol}/>,<PermissionEditor key="e"/>,<EndpointAuth key="f" protocol={protocol}/>,<CallerStep key="g"/>,
  <Result key="h" status="success" title={endpointLabel+"模拟测试通过"} subTitle="转换结构、权限策略、端点认证和调用方配置均已校验"><Space direction="vertical"><Input readOnly value={"https://gate.example.com/"+(protocol==="MCP"?"mcp":"api")+"/personal-data-readonly"}/><Tag color="success">准备发布</Tag>{protocol==="OpenAPI"?<Input readOnly value="https://gate.example.com/openapi/personal-data-readonly.json"/>:null}<Button onClick={()=>message.success("重新测试成功（Mock）")}>重新测试</Button></Space></Result>
 ];
 if(done)return <Result status="success" title={endpointLabel+"已发布"} extra={<Button type="primary" onClick={()=>router.push("/endpoints")}>返回端点发布</Button>}/>;
 return <div className={styles.wizard}><Card><div className={styles.selectedCount}><strong>{endpointLabel}</strong><span>第 {step+1}/{titles.length} 步 · {titles[step]} · 已选择 7 项能力</span></div><Steps current={step} items={titles.map(title=>({title}))}/><div className={styles.stepWrap}><h3 className={styles.stepTitle} data-testid="wizard-title">{endpointLabel} · {titles[step]}</h3>{content[step]}</div><div className={styles.actions} data-testid="wizard-actions"><Button disabled={!interactive||step===0} onClick={()=>setStep(x=>x-1)}>上一步</Button><Button type="primary" disabled={!interactive} onClick={()=>step===titles.length-1?(setDone(true),message.success("端点已发布")):setStep(x=>x+1)}>{step===titles.length-1?"测试并发布":"下一步"}</Button></div></Card></div>
}
