"use client";
import { ApiOutlined, MailOutlined, NodeIndexOutlined } from "@ant-design/icons";
import { Alert, Button, Card, Checkbox, Collapse, Drawer, Form, Input, InputNumber, Radio, Result, Select, Space, Steps, Switch, Tag, Upload, message } from "antd";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { services } from "@/mocks/data";
import type { Permission } from "@/services/contracts/gateway";
import styles from "./Gateway.module.css";

const categories=["网盘","邮箱","笔记","金融","办公","开发","其他"].map(x=>({label:x,value:x}));
const authOptions=["None","Bearer","API Key","OAuth2","Header"].map(x=>({label:x,value:x}));
const apiAuth=["None","APIKey","Basic","Bearer","OAuth1.0a","OAuth2","Header"].map(x=>({label:x,value:x}));
const permOptions=[{label:"允许",value:"allow"},{label:"每次确认",value:"confirm"},{label:"禁止",value:"deny"}];

function BasicInfo(){return <Form layout="vertical" className={styles.formGrid}><Form.Item label="服务名称" required><Input placeholder="例如：我的网盘"/></Form.Item><Form.Item label="服务标识" required><Input placeholder="my_drive"/></Form.Item><Form.Item label="分类" required><Select options={categories} placeholder="请选择"/></Form.Item><Form.Item label="图标"><Upload><Button>上传图标</Button></Upload></Form.Item><Form.Item label="说明" className={styles.span2}><Input.TextArea rows={3} placeholder="说明这个服务可以提供什么能力"/></Form.Item></Form>}
function OAuthFields(){return <div className={styles.formGrid}><Form.Item label="Authorization Endpoint"><Input placeholder="https://.../authorize"/></Form.Item><Form.Item label="Token Endpoint"><Input placeholder="https://.../token"/></Form.Item><Form.Item label="Client ID"><Input placeholder="Mock Client ID"/></Form.Item><Form.Item label="Scope"><Input placeholder="read write"/></Form.Item><Form.Item label="PKCE"><Switch defaultChecked/> 启用</Form.Item><Form.Item label="Redirect URI"><Input placeholder="https://gate.example.com/oauth/callback"/></Form.Item><Form.Item label="Access Token Expire"><InputNumber min={60} defaultValue={3600} addonAfter="秒" style={{width:"100%"}}/></Form.Item><Form.Item label="Refresh Token"><Switch defaultChecked/> 支持</Form.Item></div>}
function McpAddress(){return <Form layout="vertical"><div className={styles.formGrid}><Form.Item label="MCP Endpoint" required><Input placeholder="https://mcp.example.com/mcp"/></Form.Item><Form.Item label="Transport"><Select defaultValue="auto" options={["自动","Streamable HTTP","SSE"].map((x,i)=>({label:x,value:i?x:"auto"}))}/></Form.Item></div><Collapse ghost items={[{key:"advanced",label:"高级连接配置",children:<div className={styles.formGrid}><Form.Item label="Timeout"><InputNumber defaultValue={30} addonAfter="秒" style={{width:"100%"}}/></Form.Item><Form.Item label="Retry"><InputNumber defaultValue={2} min={0} max={5} style={{width:"100%"}}/></Form.Item><Form.Item label="TLS"><Switch defaultChecked/> 校验证书</Form.Item><Form.Item label="UserAgent"><Input defaultValue="PersonalGateway/0.2"/></Form.Item></div>}]} /></Form>}
function UpstreamAuth({api=false}:{api?:boolean}){return <Form layout="vertical"><Alert type="info" showIcon message="此处只配置上游服务认证，不是端点调用方认证。" style={{marginBottom:16}}/><Form.Item label="上游认证方式"><Select defaultValue="None" options={api?apiAuth:authOptions}/></Form.Item><Form.Item label="Mock 认证值"><Input.Password placeholder="仅 Mock，请勿填写真实 Secret"/></Form.Item>{api?<Collapse items={[{key:"oauth",label:"上游 OAuth 配置",children:<OAuthFields/>}]}/>:null}</Form>}
function TestCapabilities({mail=false,configure=false}:{mail?:boolean;configure?:boolean}){const list=mail?["搜索邮件","读取邮件","查看附件信息","下载附件","发送邮件","移动邮件","删除邮件"]:["搜索内容","读取详情","新建内容","更新内容","删除内容"];return <Space direction="vertical" size={14} style={{width:"100%"}}><Alert showIcon type="success" message={mail?"收件测试和发件测试均成功":"initialize → tools/list → 能力发现完成"} description="这是 Mock 测试结果，没有发起真实连接。"/><Space wrap><Button type="primary">测试连接</Button>{mail?<><Button>测试收件</Button><Button>测试发件</Button></>:null}</Space><Collapse items={[{key:"caps",label:"已发现 "+list.length+" 项原始能力",children:<Space direction="vertical" style={{width:"100%"}}>{list.map((x,i)=><div className={styles.capRow} key={x}><span><strong>{x}</strong><br/><small className={styles.muted}>{i<3?"只读能力":i===list.length-1?"高危能力":"写入能力"}</small></span>{configure?<Select defaultValue={(i<2?"allow":i===list.length-1?"deny":"confirm") as Permission} options={permOptions}/>:<Tag>{i<3?"只读":"写入"}</Tag>}</div>)}</Space>}]} /></Space>}
function ApiDefinition(){return <Form layout="vertical"><Form.Item label="API 定义方式"><Radio.Group defaultValue="openapi" optionType="button" buttonStyle="solid" options={[{label:"OpenAPI",value:"openapi"},{label:"手工配置",value:"manual"}]}/></Form.Item><Collapse defaultActiveKey={["openapi"]} items={[{key:"openapi",label:"OpenAPI 导入",children:<Space direction="vertical" style={{width:"100%"}}><Input placeholder="OpenAPI URL"/><Input.TextArea rows={4} placeholder="粘贴 JSON 或 YAML"/><Upload><Button>上传 JSON / YAML</Button></Upload></Space>},{key:"manual",label:"手工接口定义",children:<div className={styles.formGrid}><Form.Item label="Method"><Select defaultValue="GET" options={["GET","POST","PUT","PATCH","DELETE"].map(x=>({label:x,value:x}))}/></Form.Item><Form.Item label="Path"><Input placeholder="/v1/items/{id}"/></Form.Item><Form.Item label="Query"><Input.TextArea rows={3} placeholder="参数名称、类型、是否必填"/></Form.Item><Form.Item label="Header"><Input.TextArea rows={3} placeholder="请求头定义"/></Form.Item><Form.Item label="Body"><Input.TextArea rows={3} placeholder="JSON Body"/></Form.Item><Form.Item label="Response"><Input.TextArea rows={3} placeholder="响应示例"/></Form.Item><Form.Item label="JSONPath"><Input placeholder="$.data.items"/></Form.Item><Form.Item label="Schema"><Input.TextArea rows={3} placeholder="JSON Schema"/></Form.Item></div>}]} /></Form>}
function MailConfig({smtp=false}:{smtp?:boolean}){return <Form layout="vertical" className={styles.formGrid}><Form.Item label="Host" required><Input defaultValue={smtp?"smtp.qq.com":"imap.qq.com"}/></Form.Item><Form.Item label="Port" required><InputNumber defaultValue={smtp?465:993} style={{width:"100%"}}/></Form.Item><Form.Item label="TLS"><Switch defaultChecked/> 启用</Form.Item>{smtp?<Form.Item label="ReplyTo"><Input placeholder="可选回复地址"/></Form.Item>:null}</Form>}

export function ServiceWizard(){
 const router=useRouter();const [kind,setKind]=useState<"MCP"|"API"|"邮箱"|null>(null);const [step,setStep]=useState(0);const [done,setDone]=useState(false);
 const titles=kind==="MCP"?["基本信息","地址与传输","上游认证","测试连接","发现能力","保存"]:kind==="API"?["基本信息","API 定义","上游认证","接口预览","测试","保存"]:kind==="邮箱"?["服务商","账号与授权码","IMAP","SMTP","测试","保存"]:["选择类型"];
 useEffect(()=>{const h=(e:BeforeUnloadEvent)=>{if(!done){e.preventDefault();e.returnValue=""}};window.addEventListener("beforeunload",h);return()=>window.removeEventListener("beforeunload",h)},[done]);
 const reset=(v:"MCP"|"API"|"邮箱")=>{setKind(v);setStep(0)};
 const finish=()=>{setDone(true);message.success("服务已保存为 Mock 数据");setTimeout(()=>router.push("/services"),500)};
 const content=()=>{
  if(!kind)return <div className={styles.choiceGrid}>{[{k:"MCP",i:<NodeIndexOutlined/>,t:"MCP 服务",d:"接入已有 MCP，或将已有 API 转换为 MCP"},{k:"API",i:<ApiOutlined/>,t:"API 服务",d:"导入 OpenAPI，或手工配置完整接口"},{k:"邮箱",i:<MailOutlined/>,t:"邮箱服务",d:"快速配置 QQ、163 或通用邮箱"}].map(x=><Button key={x.k} className={styles.choice} onClick={()=>reset(x.k as "MCP"|"API"|"邮箱")}><span className={styles.serviceType}>{x.i}</span><strong>{x.t}</strong><span className={styles.muted}>{x.d}</span></Button>)}</div>;
  if(kind==="MCP"){if(step===0)return <BasicInfo/>;if(step===1)return <McpAddress/>;if(step===2)return <UpstreamAuth/>;if(step===3)return <Alert type="success" showIcon message="Mock 连接测试成功" description="initialize 响应正常。"/>;if(step===4)return <TestCapabilities/>;return <Result status="success" title="远程 MCP 服务配置就绪" subTitle="将保存原始能力 Schema 快照。"/>}
  if(kind==="API"){if(step===0)return <BasicInfo/>;if(step===1)return <ApiDefinition/>;if(step===2)return <UpstreamAuth api/>;if(step===3)return <Collapse defaultActiveKey={["ops"]} items={[{key:"ops",label:"3 个原始 API Operation",children:<Space direction="vertical"><Tag>GET /items</Tag><Tag>GET /items/:id</Tag><Tag color="warning">POST /items · 写入</Tag></Space>}]} />;if(step===4)return <Alert type="success" showIcon message="Mock 接口测试成功" description="Base URL、上游认证和响应 Schema 校验通过。"/>;return <Result status="success" title="API 服务配置就绪" subTitle="保存 Base URL、认证和原始 Operation。"/>}
  if(step===0)return <Radio.Group defaultValue="QQ邮箱" optionType="button" buttonStyle="solid" options={["QQ邮箱","163邮箱","通用邮箱"].map(x=>({label:x,value:x}))}/>;
  if(step===1)return <Form layout="vertical"><Form.Item label="邮箱地址" required><Input placeholder="name@example.com"/></Form.Item><Form.Item label="授权码" required><Input.Password placeholder="Mock 授权码，请勿输入真实信息"/></Form.Item></Form>;
  if(step===2)return <MailConfig/>;if(step===3)return <MailConfig smtp/>;if(step===4)return <TestCapabilities mail/>;return <Result status="success" title="邮箱服务配置就绪" subTitle="保存 IMAP/SMTP 连接和 7 项原始能力。"/>;
 };
 if(done)return <Result status="success" title="服务已保存" extra={<Button type="primary" onClick={()=>router.push("/services")}>返回全部服务</Button>}/>;
 return <div className={styles.wizard} data-testid="wizard"><Card><Steps current={step} items={titles.map(title=>({title}))}/><div className={styles.stepWrap}><h3 className={styles.stepTitle} data-testid="wizard-title">当前步骤：{titles[step]}</h3>{content()}</div><div className={styles.actions} data-testid="wizard-actions"><Button disabled={!kind||step===0} onClick={()=>setStep(x=>Math.max(0,x-1))}>上一步</Button><Button type="primary" disabled={!kind} onClick={()=>step===titles.length-1?finish():setStep(x=>x+1)}>{step===titles.length-1?"保存":"下一步"}</Button></div></Card></div>
}

function ServiceSelection(){return <><div className={styles.selectedCount}><strong>已选择 7 项能力</strong><span>只读能力默认选择；写入和高危能力默认不选择</span></div><Space direction="vertical" style={{width:"100%"}}>{services.map(s=><Collapse key={s.id} items={[{key:s.id,label:<Space><Checkbox defaultChecked={s.id!=="office-api"}/><strong>{s.name}</strong><Tag>{s.type} 服务</Tag></Space>,children:<Space direction="vertical" style={{width:"100%"}}>{s.capabilities.map(c=><div key={c.id} className={styles.capRow}><Checkbox defaultChecked={c.risk==="read"}><strong>{c.name}</strong><br/><small className={styles.muted}>{c.id} · {c.risk==="read"?"只读":"写入"} · {c.risk==="delete"?"高":"中"}风险</small></Checkbox><Tag color={c.risk==="read"?"success":c.risk==="delete"?"error":"warning"}>{c.risk==="read"?"默认选择":"默认不选"}</Tag></div>)}</Space>}]} />)}</Space></>}
function PermissionEditor(){return <><Alert type="info" showIcon message="服务级策略用于批量设置，最终仍保存为能力级权限。" style={{marginBottom:16}}/><Space direction="vertical" style={{width:"100%"}}>{services.slice(0,3).map(s=><Collapse key={s.id} items={[{key:s.id,label:<Space><strong>{s.name}</strong><Select defaultValue="readonly" style={{width:138}} options={[{label:"不包含该服务",value:"none"},{label:"仅允许只读",value:"readonly"},{label:"自定义",value:"custom"}]}/></Space>,children:<Space direction="vertical" style={{width:"100%"}}>{s.capabilities.map(c=><div key={c.id} className={styles.capRow}><span><strong>{c.name}</strong><br/><small className={styles.muted}>{c.description}</small></span><Select defaultValue={c.permission} options={permOptions}/></div>)}</Space>}]} />)}</Space></>}
function EndpointProtocol({protocol,setProtocol}:{protocol:string;setProtocol:(v:string)=>void}){return <div className={styles.choiceGrid}>{[{id:"MCP",title:"MCP 端点",desc:"将 MCP、API 或邮箱服务统一发布为可供 AI 客户端调用的 MCP 端点。"},{id:"OpenAPI",title:"OpenAPI API 端点",desc:"将 MCP、API 或邮箱服务统一发布为标准 HTTP API，并生成 OpenAPI 文档。"}].map(x=><Button key={x.id} type={protocol===x.id?"primary":"default"} className={styles.choice} onClick={()=>setProtocol(x.id)}><strong>{x.title}</strong><span>{x.desc}</span></Button>)}<Card className={styles.span2} size="small"><Form layout="vertical">{protocol==="MCP"?<div className={styles.formGrid}><Form.Item label="传输方式"><Select defaultValue="Streamable HTTP" options={["Streamable HTTP","SSE 兼容模式"].map(x=>({label:x,value:x}))}/></Form.Item><Form.Item label="MCP 协议版本"><Select defaultValue="2025-06-18" options={[{label:"2025-06-18",value:"2025-06-18"},{label:"2024-11-05",value:"2024-11-05"}]}/></Form.Item><Form.Item label="启用 Session"><Switch defaultChecked/></Form.Item><Form.Item label="Endpoint 路径预览"><Input readOnly value="/mcp/personal-data-readonly"/></Form.Item></div>:<div className={styles.formGrid}><Form.Item label="API Base Path"><Input defaultValue="/api/personal-data"/></Form.Item><Form.Item label="OpenAPI 文档版本"><Select defaultValue="3.1.0" options={["3.1.0","3.0.3"].map(x=>({label:x,value:x}))}/></Form.Item><Form.Item label="API 版本号"><Input defaultValue="v1"/></Form.Item><Form.Item label="Server URL 预览"><Input readOnly value="https://gate.example.com/api/personal-data"/></Form.Item><Form.Item label="OpenAPI Schema URL 预览" className={styles.span2}><Input readOnly value="https://gate.example.com/openapi/personal-data.json"/></Form.Item></div>}</Form></Card></div>}
function ConversionEditor({service,protocol}:{service:typeof services[number];protocol:string}){const [open,setOpen]=useState(false);const direction=service.type+" → "+(protocol==="MCP"?"MCP":"OpenAPI");const external=service.type==="邮箱"?(protocol==="MCP"?"search_emails":"POST /mail/search"):service.type==="API"?(protocol==="MCP"?"files_search":"GET /files/search"):(protocol==="MCP"?"market_quote":"POST /market/quote");return <><Card size="small"><div className={styles.entityTop}><div><strong>{service.name}</strong><p className={styles.muted}>{direction} · {service.capabilities.length} 项原始能力</p></div><Tag color="blue">{direction}</Tag></div><Collapse items={[{key:"preview",label:"转换结果预览",children:<ul>{service.capabilities.slice(0,3).map(c=><li key={c.id}>{c.name} → <code>{external}</code></li>)}</ul>}]} /><Button block onClick={()=>setOpen(true)}>编辑能力转换</Button></Card><Drawer open={open} onClose={()=>setOpen(false)} title={service.name+" · "+direction} width={720} placement="right"><Form layout="vertical"><Alert type="info" showIcon message={"来源服务："+service.name} description="Base URL、IMAP/SMTP 与上游认证沿用服务配置，不在端点中重复填写。" style={{marginBottom:16}}/><div className={styles.formGrid}><Form.Item label={protocol==="MCP"?"MCP Tool 名称":"对外 Operation ID"}><Input defaultValue={external.replace(/[^a-z_]/g,"_")}/></Form.Item><Form.Item label="显示名称"><Input defaultValue={service.capabilities[0].name}/></Form.Item><Form.Item label="描述" className={styles.span2}><Input.TextArea rows={2} defaultValue={service.capabilities[0].description}/></Form.Item><Form.Item label={protocol==="MCP"?"Input Schema":"参数 Schema"}><Input.TextArea className={styles.schemaEditor} rows={5} defaultValue={'{"type":"object","properties":{"query":{"type":"string"}}}'}/></Form.Item><Form.Item label={protocol==="MCP"?"Output Schema":"返回 Schema"}><Input.TextArea className={styles.schemaEditor} rows={5} defaultValue={'{"type":"object","properties":{"items":{"type":"array"}}}'}/></Form.Item></div><Collapse items={[
 {key:"request",label:service.type==="API"?"API 请求映射":"请求与参数映射",children:<div className={styles.formGrid}><Form.Item label="原始 Operation / 能力"><Input readOnly value={service.capabilities[0].id}/></Form.Item><Form.Item label="Method"><Select defaultValue={protocol==="MCP"?"GET":"POST"} options={["GET","POST","DELETE"].map(x=>({label:x,value:x}))}/></Form.Item><Form.Item label="对外 Path"><Input defaultValue={protocol==="MCP"?"/upstream/search":"/mail/search"}/></Form.Item><Form.Item label="Path 参数映射"><Input placeholder="id → path.id"/></Form.Item><Form.Item label="Query 参数映射"><Input placeholder="query → query.q"/></Form.Item><Form.Item label="Header 参数映射"><Input placeholder="仅允许安全 Header"/></Form.Item><Form.Item label="Body 参数映射" className={styles.span2}><Input.TextArea rows={3}/></Form.Item></div>},
 {key:"response",label:"返回结果与安全限制",children:<div className={styles.formGrid}><Form.Item label="成功状态码"><Input defaultValue="200, 201"/></Form.Item><Form.Item label="JSONPath"><Input defaultValue="$.data"/></Form.Item><Form.Item label="保留字段"><Input placeholder="id,title,createdAt"/></Form.Item><Form.Item label="排除字段"><Input placeholder="token,raw_headers"/></Form.Item><Form.Item label="最大返回记录数"><InputNumber defaultValue={50} style={{width:"100%"}}/></Form.Item><Form.Item label="最大响应大小"><InputNumber defaultValue={512} addonAfter="KB" style={{width:"100%"}}/></Form.Item><Form.Item label="错误码映射"><Input.TextArea rows={3}/></Form.Item><Form.Item label="敏感字段脱敏"><Switch defaultChecked/></Form.Item></div>},
 {key:"mcp",label:"协议专用选项",children:<div className={styles.formGrid}><Form.Item label="Tool 名称前缀"><Input placeholder="mail_"/></Form.Item><Form.Item label="同步上游 Schema 变更"><Switch defaultChecked/></Form.Item><Form.Item label="包含正文"><Switch/></Form.Item><Form.Item label="允许附件"><Switch/></Form.Item><Form.Item label="隐藏上游真实路径"><Switch defaultChecked/></Form.Item><Form.Item label="超时"><InputNumber defaultValue={30} addonAfter="秒"/></Form.Item></div>}
 ]}/><div className={styles.actions}><Button onClick={()=>setOpen(false)}>取消</Button><Button type="primary" onClick={()=>{setOpen(false);message.success("Mock 转换配置已保存")}}>保存转换</Button></div></Form></Drawer></>}
function ConversionStep({protocol}:{protocol:string}){return <><Alert type="info" showIcon message="转换发生在端点发布" description="根据上游服务类型与发布协议自动生成转换结果，可逐项修改名称、Schema、映射与限制。" style={{marginBottom:16}}/><div className={styles.cards}>{services.slice(0,3).map(s=><ConversionEditor key={s.id} service={s} protocol={protocol}/>)}</div></>}
function EndpointAuth({protocol}:{protocol:string}){return <Form layout="vertical"><Alert type="info" showIcon message="这里只配置下游调用方认证；上游认证由服务接入管理。" style={{marginBottom:16}}/><Form.Item label="端点认证方式"><Radio.Group defaultValue={protocol==="MCP"?"OAuth 2.1":"API Key"} options={(protocol==="MCP"?["OAuth 2.1","Bearer Token","无认证，仅开发环境"]:["API Key","Bearer Token","OAuth 2.0（预留）"]).map(x=>({label:x,value:x}))}/></Form.Item><Collapse items={[{key:"oauth",label:"OAuth 配置",children:<OAuthFields/>},{key:"key",label:"API Key 配置",children:<div className={styles.formGrid}><Form.Item label="Header 名称"><Input defaultValue="X-API-Key"/></Form.Item><Form.Item label="Key 前缀"><Input defaultValue="pg_"/></Form.Item></div>}]} /></Form>}
export function EndpointWizard(){
 const router=useRouter();const [step,setStep]=useState(0);const [protocol,setProtocol]=useState("MCP");const [done,setDone]=useState(false);const titles=["基本信息","发布协议","服务与能力","能力转换","权限策略","端点认证","调用方","测试与发布"];
 useEffect(()=>{const h=(e:BeforeUnloadEvent)=>{if(!done){e.preventDefault();e.returnValue=""}};window.addEventListener("beforeunload",h);return()=>window.removeEventListener("beforeunload",h)},[done]);
 const endpointLabel=protocol==="MCP"?"MCP 端点":"OpenAPI API 端点";
 const content=[
  <Form key="a" layout="vertical" className={styles.formGrid}><Form.Item label="端点名称" required><Input defaultValue="个人数据只读端点"/></Form.Item><Form.Item label="端点标识" required><Input defaultValue="personal-data-readonly"/></Form.Item><Form.Item label="图标"><Upload><Button>上传图标</Button></Upload></Form.Item><Form.Item label="状态"><Radio.Group defaultValue="draft" options={[{label:"草稿",value:"draft"},{label:"启用",value:"enabled"}]}/></Form.Item><Form.Item label="说明" className={styles.span2}><Input.TextArea rows={3}/></Form.Item></Form>,
  <EndpointProtocol key="b" protocol={protocol} setProtocol={setProtocol}/>,
  <ServiceSelection key="c"/>,<ConversionStep key="d" protocol={protocol}/>,<PermissionEditor key="e"/>,<EndpointAuth key="f" protocol={protocol}/>,
  <Form key="g" layout="vertical"><Alert type="info" showIcon message="一个端点允许多个调用方；每个调用方拥有独立身份、凭证、统计、授权和日志。" style={{marginBottom:16}}/><div className={styles.formGrid}><Form.Item label="AI 厂商"><Select mode="multiple" options={["OpenAI","Anthropic","xAI","Alibaba","Google","Microsoft","Other"].map(x=>({label:x,value:x}))}/></Form.Item><Form.Item label="调用方名称"><Select mode="tags" options={["ChatGPT","Claude","Grok","Gemini","通义千问","私人 GPT","自定义"].map(x=>({label:x,value:x}))}/></Form.Item></div><Button type="dashed" block>添加另一个调用方</Button></Form>,
  <Result key="h" status="success" title={endpointLabel+" Mock 测试通过"} subTitle="转换 Schema、权限策略、端点认证和调用方配置均已校验"><Space direction="vertical"><Input readOnly value={"https://gate.example.com/"+(protocol==="MCP"?"mcp":"api")+"/personal-data-readonly"}/><Tag color="success">准备发布</Tag>{protocol==="OpenAPI"?<Input readOnly value="https://gate.example.com/openapi/personal-data-readonly.json"/>:null}<Button>重新测试</Button></Space></Result>
 ];
 if(done)return <Result status="success" title={endpointLabel+"已发布"} extra={<Button type="primary" onClick={()=>router.push("/endpoints")}>返回端点发布</Button>}/>;
 return <div className={styles.wizard}><Card><div className={styles.selectedCount}><strong>{endpointLabel}</strong><span>第 {step+1}/8 步 · {titles[step]} · 已选择 7 项能力</span></div><Steps current={step} items={titles.map(title=>({title}))}/><div className={styles.stepWrap}><h3 className={styles.stepTitle} data-testid="wizard-title">{endpointLabel} · {titles[step]}</h3>{content[step]}</div><div className={styles.actions} data-testid="wizard-actions"><Button disabled={step===0} onClick={()=>setStep(x=>x-1)}>上一步</Button><Button type="primary" onClick={()=>step===titles.length-1?(setDone(true),message.success("端点已发布")):setStep(x=>x+1)}>{step===titles.length-1?"测试并发布":"下一步"}</Button></div></Card></div>
}
